// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const createQuestion = `-- name: CreateQuestion :one
INSERT INTO question 
  ("room_id", "text")
  VALUES ($1, $2)
RETURNING "id", "room_id", "text", "reaction_count", "answered", "created_at", "updated_at"
`

type CreateQuestionParams struct {
	RoomID uuid.UUID
	Text   string
}

func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error) {
	row := q.db.QueryRow(ctx, createQuestion, arg.RoomID, arg.Text)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.Text,
		&i.ReactionCount,
		&i.Answered,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRoom = `-- name: CreateRoom :one
INSERT INTO room 
  ("name") VALUES
  ($1)
RETURNING "id", "name", "created_at", "updated_at"
`

func (q *Queries) CreateRoom(ctx context.Context, name string) (Room, error) {
	row := q.db.QueryRow(ctx, createRoom, name)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQuestion = `-- name: GetQuestion :one
SELECT
    "id", "room_id", "text", "reaction_count", "answered", "created_at", "updated_at"
FROM question
WHERE "id" = $1
`

func (q *Queries) GetQuestion(ctx context.Context, id uuid.UUID) (Question, error) {
	row := q.db.QueryRow(ctx, getQuestion, id)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.Text,
		&i.ReactionCount,
		&i.Answered,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoom = `-- name: GetRoom :one
SELECT 
    "id", "name", "created_at", "updated_at"
FROM room
WHERE "id" = $1
`

func (q *Queries) GetRoom(ctx context.Context, id uuid.UUID) (Room, error) {
	row := q.db.QueryRow(ctx, getRoom, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoomQuestions = `-- name: GetRoomQuestions :many
SELECT
    "id", "room_id", "text", "reaction_count", "answered", "created_at", "updated_at"
FROM question
WHERE "room_id" = $1
`

func (q *Queries) GetRoomQuestions(ctx context.Context, roomID uuid.UUID) ([]Question, error) {
	rows, err := q.db.Query(ctx, getRoomQuestions, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Question
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.Text,
			&i.ReactionCount,
			&i.Answered,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRooms = `-- name: GetRooms :many
SELECT 
    "id", "name", "created_at", "updated_at"
FROM room
`

func (q *Queries) GetRooms(ctx context.Context) ([]Room, error) {
	rows, err := q.db.Query(ctx, getRooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markQuestionAsAnswered = `-- name: MarkQuestionAsAnswered :exec
UPDATE question
SET
    "answered" = true
WHERE "id" = $1
`

func (q *Queries) MarkQuestionAsAnswered(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markQuestionAsAnswered, id)
	return err
}

const reactToQuestion = `-- name: ReactToQuestion :one
UPDATE question
SET
    "reaction_count" = "reaction_count" + 1
WHERE "id" = $1
RETURNING "reaction_count"
`

func (q *Queries) ReactToQuestion(ctx context.Context, id uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, reactToQuestion, id)
	var reaction_count int64
	err := row.Scan(&reaction_count)
	return reaction_count, err
}

const removeReactionFromQuestion = `-- name: RemoveReactionFromQuestion :one
UPDATE question
SET
    "reaction_count" = "reaction_count" - 1
WHERE "id" = $1
RETURNING "reaction_count"
`

func (q *Queries) RemoveReactionFromQuestion(ctx context.Context, id uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, removeReactionFromQuestion, id)
	var reaction_count int64
	err := row.Scan(&reaction_count)
	return reaction_count, err
}
